name: Run Tests
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Set npm config
        run: echo legacy-peer-deps=true > ~/.npmrc

      - name: Install and Tests
        run: |
          npm ci
          npm test

      - name: Check test result
        if: ${{ failure() }}
        run: exit 1
